name: stock_management
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.5.1

  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.3

  http: ^1.2.1
  connectivity_plus: ^6.0.5
  network_info_plus: ^6.0.2

  flutter_blue_plus: ^1.35.5

  print_bluetooth_thermal: ^1.1.6
  esc_pos_utils_plus: ^2.0.4
  esc_pos_printer_plus: ^0.1.1
  flutter_usb_printer: ^0.3.1

  mobile_scanner: ^5.2.3

  image_picker: ^1.1.2
  image_cropper: ^12.2.1
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.0

  image: ^4.2.0

  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^10.0.2

  multicast_dns: ^0.3.3
  dart_ping: ^9.0.1
 
  qr_flutter: ^4.1.0

  
  

  permission_handler: ^12.0.1

  audioplayers: ^6.0.0

  mailer: ^6.0.1

  fl_chart: ^0.68.0
  collection: ^1.19.1
  url_launcher: ^6.3.0
  intl: ^0.19.0 
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.1
  csv: ^6.0.0
  workmanager: ^0.6.0
  file_picker: ^11.0.2
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Moved flutter_launcher_icons here as a development dependency
  flutter_launcher_icons: ^0.14.3 

# ─── ADD THIS SPECIFIC LAUNCHER ICONS CONFIGURATION BLOCK ───
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image.png
    - assets/inventory.png
    - assets/sounds/scanner_beep.mp3
   