import 'dart:convert';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:http/http.dart' as http;
import '../network/api_config.dart';

@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
}

class NotificationService {
  static final FirebaseMessaging _messaging = FirebaseMessaging.instance;
  static final FlutterLocalNotificationsPlugin _notificationsPlugin =
      FlutterLocalNotificationsPlugin();

  static Future<void> initialize() async {
    // 1. Background message handler
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

    // 2. Local notifications initialization
    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/launcher_icon');

    const InitializationSettings initializationSettings =
        InitializationSettings(android: initializationSettingsAndroid);

    await _notificationsPlugin.initialize(initializationSettings);

    const AndroidNotificationChannel channel = AndroidNotificationChannel(
      'high_importance_channel',
      'Stock Management Notifications',
      description: 'Channel for stock management app notifications',
      importance: Importance.max,
    );

    await _notificationsPlugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(channel);

    // 3. Request push permissions & configure foreground display
    NotificationSettings settings = await _messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
    );

    if (settings.authorizationStatus == AuthorizationStatus.authorized) {
      await _messaging.setForegroundNotificationPresentationOptions(
        alert: true,
        badge: true,
        sound: true,
      );

      // Listen for foreground FCM pushes
      FirebaseMessaging.onMessage.listen((RemoteMessage message) {
        _showFcmForegroundNotification(message);
      });
    }
  }

  // Call this method right after successful user login to sync the FCM token
  static Future<void> registerFcmToken(int userId) async {
    try {
      String? token = await _messaging.getToken();
      if (token != null) {
        await _postTokenToBackend(userId, token);
      }

      _messaging.onTokenRefresh.listen((newToken) {
        _postTokenToBackend(userId, newToken);
      });
    } catch (e) {
      // Quietly handle network exceptions
    }
  }

static Future<void> _postTokenToBackend(
  int userId,
  String token,
) async {
  final response = await http.post(
    Uri.parse(ApiConfig.saveFcmToken),
    headers: ApiConfig.jsonHeaders,
    body: jsonEncode({
      'user_id': userId,
      'fcm_token': token,
      'device_type': 'android',
    }),
  );

  if (response.statusCode != 200) {
    throw Exception(
      'Failed to save FCM token. '
      'HTTP ${response.statusCode}',
    );
  }

  final data = jsonDecode(response.body);

  if (data['success'] != true) {
    throw Exception(
      data['message'] ?? 'Failed to save FCM token',
    );
  }
}
  
static Future<void> _showFcmForegroundNotification(
  RemoteMessage message,
) async {
  final RemoteNotification? notification = message.notification;

  if (notification == null) {
    return;
  }

  final String title =
      notification.title ?? "⚠️ Low Stock Alert";

  final String body =
      notification.body ??
      "An item in your inventory is running low.";

  // Use the unique notification ID generated by the backend.
  // This prevents multiple notifications from replacing each other.
  final String? notificationId =
      message.data['notification_id']?.toString();

  int androidNotificationId;

  if (notificationId != null && notificationId.isNotEmpty) {
    androidNotificationId =
        int.tryParse(notificationId) ?? message.hashCode;
  } else {
    // Safe fallback for notifications that do not contain
    // a backend notification_id.
    androidNotificationId = message.hashCode;
  }

  await _notificationsPlugin.show(
    androidNotificationId,
    title,
    body,
    NotificationDetails(
      android: AndroidNotificationDetails(
        'high_importance_channel',
        'Stock Management Notifications',
        channelDescription:
            'Channel for inventory alerts and notifications',
        icon: '@mipmap/launcher_icon',
        importance: Importance.max,
        priority: Priority.high,
        styleInformation: BigTextStyleInformation(
          body,
          contentTitle: title,
          summaryText: 'Inventory Alert',
        ),
      ),
      iOS: const DarwinNotificationDetails(
        presentAlert: true,
        presentBadge: true,
        presentSound: true,
      ),
    ),
  );
}

  // Existing backup notification method
  static Future<void> showBackupNotification() async {
    const AndroidNotificationDetails
    androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'stock_management_channel',
      'Stock Management Notifications',
      channelDescription: 'Channel for stock management app notifications',
      importance: Importance.max,
      priority: Priority.high,
      ticker: 'ticker',
      icon: 'ic_notification',
      color: Color(0xFF0033A0),
    );

    const NotificationDetails platformChannelSpecifics = NotificationDetails(
      android: androidPlatformChannelSpecifics,
    );

    await _notificationsPlugin.show(
      0,
      'Backup Complete',
      'Your data has been successfully backed up to Google Drive.',
      platformChannelSpecifics,
    );
  }
}